
########

# This is how the git Makefile detects the OS:
# http://git.kernel.org/cgit/git/git.git/tree/Makefile?id=c965c029330b1f81cc107c5d829e7fd79c61d8ea#n175
uname_S := $(shell sh -c 'uname -s 2>/dev/null || echo not')

ifeq ($(uname_S),Darwin)
	OS = osx
endif

ifeq ($(uname_S),Linux)
	OS = ubuntu-x86_64
endif


########


LIB_BUILD = lib-build/$(OS)
LIB_SRC = lib-src



########

FLINT_VERSION =   flint-2.3
FLINT_SRC     =   $(LIB_SRC)/flint

FLINT_BUILD   =   $(LIB_BUILD)/flint
IDIRS        += -I$(FLINT_BUILD)/include/flint
FLINT_LIB     =   $(FLINT_BUILD)/lib/libflint.a
STATIC_LIBS  +=   $(FLINT_LIB)

########

MPFR_VERSION =   mpfr-3.1.2
MPFR_SRC     =   $(LIB_SRC)/mpfr

MPFR_BUILD    =   $(LIB_BUILD)/mpfr
# IDIRS        += -I$(MPFR_BUILD)/include
MPFR_LIB      =   $(MPFR_BUILD)/lib/libmpfr.a
STATIC_LIBS  +=   $(MPFR_LIB)

########

MPIR_VERSION =   mpir-2.3.1
MPIR_SRC     =   $(LIB_SRC)/mpir

MPIR_BUILD    =   $(LIB_BUILD)/mpir
IDIRS        += -I$(MPIR_BUILD)/include
MPIR_LIB      =   $(MPIR_BUILD)/lib/libmpir.a
STATIC_LIBS  +=   $(MPIR_LIB)



########


include Makefile.lib.build
