
########


include Makefile.os

LIB_BUILD = lib-build-$(OS)
LIB_SRC = lib-src


########

FLINT_VERSION =   flint-2.4.4
FLINT_SRC     =   $(LIB_SRC)/flint

FLINT_BUILD   =   $(LIB_BUILD)/flint
IDIRS        += -I$(FLINT_BUILD)/include/flint
FLINT_LIB     =   $(FLINT_BUILD)/lib/libflint.a
STATIC_LIBS  +=   $(FLINT_LIB)

########

MPFR_VERSION =   mpfr-3.1.2
MPFR_SRC     =   $(LIB_SRC)/mpfr

MPFR_BUILD    =   $(LIB_BUILD)/mpfr
IDIRS        += -I$(MPFR_BUILD)/include
MPFR_LIB      =   $(MPFR_BUILD)/lib/libmpfr.a
STATIC_LIBS  +=   $(MPFR_LIB)

########

# mpir-2.6.0 fails to build on OSX with clang (default compiler)
# https://groups.google.com/forum/#!topic/mpir-devel/ydcKGV-EYlg

MPIR_VERSION =   mpir-2.3.1
MPIR_SRC     =   $(LIB_SRC)/mpir

MPIR_BUILD    =   $(LIB_BUILD)/mpir
IDIRS        += -I$(MPIR_BUILD)/include
MPIR_LIB      =   $(MPIR_BUILD)/lib/libmpir.a
STATIC_LIBS  +=   $(MPIR_LIB)



########


include Makefile.lib.build
